<?php

/**
 * @file
 * Sentiment module file.
 */

 use Sentiment\Analyzer;
 use \Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function sentiment_theme($existing, $type, $theme, $path) {
  return [
      'analyzer' => [
        'template' => 'analyzer',
        'variables' => [
          'variables' => [],
          'title' => NULL,
        ],
      ],
  ];
}
function sentiment_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

    if ($entity instanceof Drupal\comment\CommentInterface) {

      // Calling Toxicity services
      $detoxifyService = \Drupal::service('sentiment.detoxify');
      $PerspectiveService = \Drupal::service('sentiment.perspective');
      $analyzerPHP = new Analyzer();

      // Preparing text
      $commentBody = str_replace("&nbsp;", '', strip_tags($entity->get('comment_body')->getValue()[0]['value']));
      $commentText = $entity->getSubject() . ': ' . $commentBody;

      // Analyzing text
      // PHP sentiment Analyzer
      $resPHP = $analyzerPHP->getSentiment($commentText);
      // Detoxify
      $resDetox = $detoxifyService->analyzer($commentText);
      // Google perspective API
      $resPerspective = $PerspectiveService->analyzer($commentText);

      // save data
      $node = Node::create([
        'type'        => 'toxicity_evaluation',
        'title'       => $entity->getSubject(),
        'field_detoxify_result' => $resDetox['TOXICITY'],
        'field_vader_result' => (1 + $resPHP['compound'])/2,
        'field_perspective_result' => $resPerspective['attributeScores']['TOXICITY']['summaryScore']['value'],
        'field_comment_reference' => $entity->id()
      ]);
      $node->save();

      \Drupal::logger('Sentiment')->notice('<pre><code>' . print_r($resDetox, TRUE) . '</code></pre>');
      \Drupal::logger('Sentiment')->notice('<pre><code>' . print_r($resPerspective, TRUE) . '</code></pre>');
      \Drupal::logger('Sentiment')->notice('<pre><code>' . print_r($resPHP, TRUE) . '</code></pre>');
    }

}
